crock_character_list:
    resource: "@CrockCharacterListBundle/Resources/config/routing.yml"
    prefix:   /character-list

crock_star_ship_manager:
    resource: "@CrockStarShipManagerBundle/Resources/config/routing.yml"
    prefix:   /star-ship-manager

index:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: index.html.twig

login:
    path: /login
    defaults:
        _controller: CrockUserBundle:Security:login

login_check:
    path: /login_check

logout:
    path: /logout