services:
    crock_characterlist.starwarslist:
        class: Crock\CharacterListBundle\StarWarsList\CrockStarWarsList

    crock_characterlist.twig.filmsfilter_extension:
        class: Crock\CharacterListBundle\Twig\FilmsFilterExtension
        tags:
        - { name: twig.extension }